## Transportkosten

**Doelstelling:**
Minimaliseer de totale transportkosten bij het bepalen van de optimale route van goederen van magazijnen naar klanten.

**Doelstelling Functie:**
$$ \text{Minimaliseer} \quad C = \sum_{i=1}^{N} \sum_{j=1}^{M} c_{ij} \cdot x_{ij}$$

waar:
- $ C $ de totale transportkosten zijn,
- $c_{ij} $ de kosten zijn van het transporteren van goederen van magazijn $i$ naar klant $j$,
- $x_{ij} $ een beslissingsvariabele is die aangeeft of goederen worden getransporteerd van magazijn $i$ naar klant $j$ (1 als wel, 0 indien niet).

**Beperkingen:**
$ \text{Onderhevig aan} \quad \sum_{i=1}^{N} x_{ij} = 1 \quad \text{voor elke klant } j $, 
$ \sum_{j=1}^{M} x_{ij} \leq 1 \quad \text{voor elk magazijn } i $, 
$ x_{ij} \in \{0, 1\} \quad \text{binaire beperkingen} $

Het doel is om de totale transportkosten te minimaliseren door elke klant toe te wijzen aan exact één magazijn en ervoor te zorgen dat elk magazijn hoogstens één klant bedient.

Concrete waardes:
- de matrix met de transportkosten tussen de verschillende locaties, is gegeven door 

In [2]:
import numpy as np
cost_matrix = np.array([[0.0, 0.55, 0.32],
                        [0.51, 0.0, 0.20],
                        [0.32, 0.20, 0.0]])

In [4]:
import numpy as np
import osqp
from scipy.sparse import csr_matrix

# Aantal magazijnen en klanten
num_warehouses = 5
num_customers = 5

# Willekeurige kostenmatrix genereren
cost_matrix = np.random.randint(1, 10, size=(num_warehouses, num_customers))
print(cost_matrix)


[[4 4 6 2 2]
 [3 6 5 3 4]
 [9 4 1 6 8]
 [5 8 7 6 3]
 [4 2 2 9 6]]


In [5]:
# Doelstelling functie
P = csr_matrix(np.kron(np.eye(num_warehouses), cost_matrix))
q = np.zeros(num_warehouses * num_customers)

In [6]:
P

<25x25 sparse matrix of type '<class 'numpy.float64'>'
	with 125 stored elements in Compressed Sparse Row format>

In [7]:
q

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# Beperkingen: elke klant moet worden toegewezen aan exact één magazijn
A_eq = np.kron(np.eye(num_customers), np.ones((1, num_warehouses)))
b_eq = np.ones(num_customers)

A_eq

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [10]:
b_eq

array([1., 1., 1., 1., 1.])

In [ ]:
# Beperkingen: elk magazijn kan hoogstens één klant bedienen
A_leq = np.kron(np.ones((1, num_customers)), np.eye(num_warehouses))
b_leq = np.ones(num_warehouses)

# Binaire beperkingen
l = np.zeros(num_warehouses * num_customers)
u = np.ones(num_warehouses * num_customers)